stages:
  - lint
  - test
  - sync

# Lint JavaScript using ESLint
eslint:
  stage: lint
  image: node:18
  script:
    - npm ci || npm install
    - npx eslint . --ext .js
  only:
    - main

phpunit:
  stage: test
  image: php:8.2
  services:
    - name: mysql:8.0
      alias: mysql

  variables:
    DB_HOST: mysql
    DB_PORT: 3306
    DB_USER: root
    DB_PASS: mysql
    DB_NAME: frugal_company
    MYSQL_ROOT_PASSWORD: mysql

  before_script:
    - apt-get update && apt-get install -y unzip git curl default-mysql-client
    - docker-php-ext-install mysqli
    - curl -sS https://getcomposer.org/installer | php
    - php composer.phar install
    - echo "Waiting for MySQL to be ready..."
    - until mysql -hmysql -uroot -pmysql -e "SELECT 1"; do sleep 1; done
    - echo "MySQL is ready. Creating database..."
    - mysql -hmysql -uroot -pmysql -e "CREATE DATABASE IF NOT EXISTS frugal_company;"
    - mysql -hmysql -uroot -pmysql frugal_company < frugal_company.sql

  script:
    - php vendor/bin/phpunit
    - php vendor/bin/phpunit --testdox

  only:
    - main

# Run Jest JavaScript tests
jest:
  stage: test
  image: node:18
  script:
    - npm ci || npm install
    - npm test
  only:
    - main

# Sync GitLab repo to GitHub
sync-to-github:
  stage: sync
  image: alpine:latest
  before_script:
    - apk add --no-cache git
  script:
    - git config --global user.email "mi222tn@student.lnu.se"
    - git config --global user.name "Mohammed Ibrahim"
    - echo "Fetching existing remotes:"
    - git remote -v
    - git remote | grep github && git remote remove github || echo "No existing 'github' remote found."
    - git remote add github https://Mohammed-Ibrahim-lnu:$GITHUB_TOKEN@github.com/Mohammed-Ibrahim-lnu/newproject.git
    - echo "Final remotes after adding github:"
    - git remote -v
    - echo "Pushing current HEAD to GitHub 'main' branch..."
    - git push github HEAD:main
  rules:
    - if: $CI_COMMIT_BRANCH == "main"

