stages:
  - sync

# Sync GitLab repo to GitHub
sync-to-github:
  stage: sync
  image: alpine:latest
  before_script:
    - apk add --no-cache git
  script:
    - git config --global user.email "mi222tn@student.lnu.se"
    - git config --global user.name "Mohammed Ibrahim"
    - echo "Fetching existing remotes:"
    - git remote -v
    - git remote | grep github && git remote remove github || echo "No existing 'github' remote found."
    - git remote add github https://Mohammed-Ibrahim-lnu:$GITHUB_TOKEN@github.com/Mohammed-Ibrahim-lnu/newproject.git
    - echo "Final remotes after adding github:"
    - git remote -v
    - echo "Pushing current HEAD to GitHub 'main' branch..."
    - git push github HEAD:main
  rules:
    - if: $CI_COMMIT_BRANCH == "main"

