stages:
  - lint
  - test
  - sync

# Lint JavaScript using ESLint
eslint:
  stage: lint
  image: node:18
  script:
    - npm ci || npm install
    - npx eslint . --ext .js
  only:
    - main

# Run PHP unit tests
phpunit:
  stage: test
  image: php:8.2
  before_script:
    - apt-get update && apt-get install -y unzip git curl
    - curl -sS https://getcomposer.org/installer | php
    - php composer.phar install
  script:
    - php vendor/bin/phpunit
  only:
    - main

# Run Jest JavaScript tests
jest:
  stage: test
  image: node:18
  script:
    - npm ci || npm install
    - npm test
  only:
    - main

# Sync GitLab repo to GitHub
sync-to-github:
  stage: sync
  image: alpine:latest
  before_script:
    - apk add --no-cache git
  script:
    - git config --global user.email "mi222tn@student.lnu.se"
    - git config --global user.name "Mohammed Ibrahim"
    - echo "Fetching existing remotes:"
    - git remote -v
    - git remote | grep github && git remote remove github || echo "No existing 'github' remote found."
    - git remote add github https://Mohammed-Ibrahim-lnu:$GITHUB_TOKEN@github.com/Mohammed-Ibrahim-lnu/newproject.git
    - echo "Final remotes after adding github:"
    - git remote -v
    - echo "Pushing current HEAD to GitHub 'main' branch..."
    - git push github HEAD:main
  rules:
    - if: $CI_COMMIT_BRANCH == "main"

